# ==============================================================================
# Merged Lakeflow Source: github
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/github/github_schemas.py
    ########################################################

    USER_STRUCT = StructType(
        [
            StructField("login", StringType(), True),
            StructField("id", LongType(), True),
            StructField("node_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("site_admin", BooleanType(), True),
        ]
    )
    """Nested user/assignee struct schema used across multiple tables."""

    PERMISSIONS_STRUCT = StructType(
        [
            StructField("admin", BooleanType(), True),
            StructField("push", BooleanType(), True),
            StructField("pull", BooleanType(), True),
        ]
    )
    """Permissions struct schema for repositories and collaborators."""

    LABEL_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("node_id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("color", StringType(), True),
            StructField("description", StringType(), True),
            StructField("default", BooleanType(), True),
        ]
    )
    """Label struct schema used in issues."""

    MILESTONE_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("number", LongType(), True),
            StructField("title", StringType(), True),
            StructField("description", StringType(), True),
            StructField("state", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("due_on", StringType(), True),
        ]
    )
    """Milestone struct schema used in issues."""

    LICENSE_STRUCT = StructType(
        [
            StructField("key", StringType(), True),
            StructField("name", StringType(), True),
            StructField("spdx_id", StringType(), True),
            StructField("url", StringType(), True),
            StructField("node_id", StringType(), True),
        ]
    )
    """License struct schema used in repositories."""

    TEMPLATE_REPOSITORY_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("node_id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("full_name", StringType(), True),
        ]
    )
    """Template repository struct schema."""

    COMMIT_REF_STRUCT = StructType(
        [
            StructField("sha", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )
    """Commit reference struct schema used in branches."""


    # =============================================================================
    # Table Schema Definitions
    # =============================================================================

    ISSUES_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("number", LongType(), False),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("title", StringType(), True),
            StructField("body", StringType(), True),
            StructField("state", StringType(), True),
            StructField("locked", BooleanType(), True),
            StructField("comments", LongType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("closed_at", StringType(), True),
            StructField("author_association", StringType(), True),
            StructField("url", StringType(), True),
            StructField("html_url", StringType(), True),
            StructField("labels_url", StringType(), True),
            StructField("comments_url", StringType(), True),
            StructField("events_url", StringType(), True),
            StructField("timeline_url", StringType(), True),
            StructField("state_reason", StringType(), True),
            StructField("user", USER_STRUCT, True),
            StructField("assignee", USER_STRUCT, True),
            StructField("assignees", ArrayType(USER_STRUCT, True), True),
            StructField("labels", ArrayType(LABEL_STRUCT, True), True),
            StructField("milestone", MILESTONE_STRUCT, True),
            StructField("pull_request", MapType(StringType(), StringType(), True), True),
            StructField("reactions", MapType(StringType(), StringType(), True), True),
        ]
    )
    """Schema for the issues table."""

    REPOSITORIES_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("name", StringType(), True),
            StructField("full_name", StringType(), True),
            StructField("owner", USER_STRUCT, True),
            StructField("private", BooleanType(), True),
            StructField("html_url", StringType(), True),
            StructField("description", StringType(), True),
            StructField("fork", BooleanType(), True),
            StructField("url", StringType(), True),
            StructField("archive_url", StringType(), True),
            StructField("assignees_url", StringType(), True),
            StructField("blobs_url", StringType(), True),
            StructField("branches_url", StringType(), True),
            StructField("collaborators_url", StringType(), True),
            StructField("comments_url", StringType(), True),
            StructField("commits_url", StringType(), True),
            StructField("compare_url", StringType(), True),
            StructField("contents_url", StringType(), True),
            StructField("contributors_url", StringType(), True),
            StructField("deployments_url", StringType(), True),
            StructField("downloads_url", StringType(), True),
            StructField("events_url", StringType(), True),
            StructField("forks_url", StringType(), True),
            StructField("git_commits_url", StringType(), True),
            StructField("git_refs_url", StringType(), True),
            StructField("git_tags_url", StringType(), True),
            StructField("git_url", StringType(), True),
            StructField("issue_comment_url", StringType(), True),
            StructField("issue_events_url", StringType(), True),
            StructField("issues_url", StringType(), True),
            StructField("keys_url", StringType(), True),
            StructField("labels_url", StringType(), True),
            StructField("languages_url", StringType(), True),
            StructField("merges_url", StringType(), True),
            StructField("milestones_url", StringType(), True),
            StructField("notifications_url", StringType(), True),
            StructField("pulls_url", StringType(), True),
            StructField("releases_url", StringType(), True),
            StructField("ssh_url", StringType(), True),
            StructField("stargazers_url", StringType(), True),
            StructField("statuses_url", StringType(), True),
            StructField("subscribers_url", StringType(), True),
            StructField("subscription_url", StringType(), True),
            StructField("tags_url", StringType(), True),
            StructField("teams_url", StringType(), True),
            StructField("trees_url", StringType(), True),
            StructField("clone_url", StringType(), True),
            StructField("mirror_url", StringType(), True),
            StructField("hooks_url", StringType(), True),
            StructField("svn_url", StringType(), True),
            StructField("homepage", StringType(), True),
            StructField("language", StringType(), True),
            StructField("forks_count", LongType(), True),
            StructField("stargazers_count", LongType(), True),
            StructField("watchers_count", LongType(), True),
            StructField("size", LongType(), True),
            StructField("default_branch", StringType(), True),
            StructField("open_issues_count", LongType(), True),
            StructField("is_template", BooleanType(), True),
            StructField("topics", ArrayType(StringType(), True), True),
            StructField("has_issues", BooleanType(), True),
            StructField("has_projects", BooleanType(), True),
            StructField("has_wiki", BooleanType(), True),
            StructField("has_pages", BooleanType(), True),
            StructField("has_downloads", BooleanType(), True),
            StructField("archived", BooleanType(), True),
            StructField("disabled", BooleanType(), True),
            StructField("visibility", StringType(), True),
            StructField("pushed_at", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("permissions", PERMISSIONS_STRUCT, True),
            StructField("allow_rebase_merge", BooleanType(), True),
            StructField("template_repository", TEMPLATE_REPOSITORY_STRUCT, True),
            StructField("temp_clone_token", StringType(), True),
            StructField("allow_squash_merge", BooleanType(), True),
            StructField("allow_merge_commit", BooleanType(), True),
            StructField("subscribers_count", LongType(), True),
            StructField("network_count", LongType(), True),
            StructField("license", LICENSE_STRUCT, True),
        ]
    )
    """Schema for the repositories table."""

    PULL_REQUESTS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("number", LongType(), False),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("state", StringType(), True),
            StructField("title", StringType(), True),
            StructField("body", StringType(), True),
            StructField("draft", BooleanType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("closed_at", StringType(), True),
            StructField("merged_at", StringType(), True),
            StructField("merge_commit_sha", StringType(), True),
            StructField("user", USER_STRUCT, True),
            StructField("base", MapType(StringType(), StringType(), True), True),
            StructField("head", MapType(StringType(), StringType(), True), True),
            StructField("html_url", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )
    """Schema for the pull_requests table."""

    COMMENTS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("issue_url", StringType(), True),
            StructField("html_url", StringType(), True),
            StructField("body", StringType(), True),
            StructField("user", USER_STRUCT, True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("author_association", StringType(), True),
        ]
    )
    """Schema for the comments table."""

    COMMITS_SCHEMA = StructType(
        [
            StructField("sha", StringType(), False),
            StructField("node_id", StringType(), True),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("commit_message", StringType(), True),
            StructField("commit_author_name", StringType(), True),
            StructField("commit_author_email", StringType(), True),
            StructField("commit_author_date", StringType(), True),
            StructField("commit_committer_name", StringType(), True),
            StructField("commit_committer_email", StringType(), True),
            StructField("commit_committer_date", StringType(), True),
            StructField("html_url", StringType(), True),
            StructField("url", StringType(), True),
            StructField("author", USER_STRUCT, True),
            StructField("committer", USER_STRUCT, True),
        ]
    )
    """Schema for the commits table."""

    USERS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("login", StringType(), False),
            StructField("node_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("site_admin", BooleanType(), True),
            StructField("name", StringType(), True),
            StructField("company", StringType(), True),
            StructField("blog", StringType(), True),
            StructField("location", StringType(), True),
            StructField("email", StringType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
        ]
    )
    """Schema for the users table."""

    ORGANIZATIONS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("login", StringType(), False),
            StructField("node_id", StringType(), True),
            StructField("url", StringType(), True),
            StructField("repos_url", StringType(), True),
            StructField("events_url", StringType(), True),
            StructField("hooks_url", StringType(), True),
            StructField("issues_url", StringType(), True),
            StructField("members_url", StringType(), True),
            StructField("public_members_url", StringType(), True),
            StructField("avatar_url", StringType(), True),
            StructField("description", StringType(), True),
        ]
    )
    """Schema for the organizations table."""

    TEAMS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("organization_login", StringType(), False),
            StructField("name", StringType(), True),
            StructField("slug", StringType(), True),
            StructField("description", StringType(), True),
            StructField("privacy", StringType(), True),
            StructField("permission", StringType(), True),
        ]
    )
    """Schema for the teams table."""

    ASSIGNEES_SCHEMA = StructType(
        [
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("login", StringType(), False),
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("site_admin", BooleanType(), True),
        ]
    )
    """Schema for the assignees table."""

    COLLABORATORS_SCHEMA = StructType(
        [
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("login", StringType(), False),
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("site_admin", BooleanType(), True),
            StructField("permissions", PERMISSIONS_STRUCT, True),
        ]
    )
    """Schema for the collaborators table."""

    BRANCHES_SCHEMA = StructType(
        [
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("name", StringType(), False),
            StructField("commit", COMMIT_REF_STRUCT, True),
            StructField("protected", BooleanType(), True),
            StructField("protection_url", StringType(), True),
        ]
    )
    """Schema for the branches table."""

    REVIEWS_SCHEMA = StructType(
        [
            StructField("id", LongType(), False),
            StructField("node_id", StringType(), True),
            StructField("repository_owner", StringType(), False),
            StructField("repository_name", StringType(), False),
            StructField("pull_number", LongType(), False),
            StructField("state", StringType(), True),
            StructField("body", StringType(), True),
            StructField("user", USER_STRUCT, True),
            StructField("commit_id", StringType(), True),
            StructField("submitted_at", StringType(), True),
            StructField("html_url", StringType(), True),
        ]
    )
    """Schema for the reviews table."""


    # =============================================================================
    # Schema Mapping
    # =============================================================================

    TABLE_SCHEMAS: dict[str, StructType] = {
        "issues": ISSUES_SCHEMA,
        "repositories": REPOSITORIES_SCHEMA,
        "pull_requests": PULL_REQUESTS_SCHEMA,
        "comments": COMMENTS_SCHEMA,
        "commits": COMMITS_SCHEMA,
        "users": USERS_SCHEMA,
        "organizations": ORGANIZATIONS_SCHEMA,
        "teams": TEAMS_SCHEMA,
        "assignees": ASSIGNEES_SCHEMA,
        "collaborators": COLLABORATORS_SCHEMA,
        "branches": BRANCHES_SCHEMA,
        "reviews": REVIEWS_SCHEMA,
    }
    """Mapping of table names to their StructType schemas."""


    # =============================================================================
    # Table Metadata Definitions
    # =============================================================================

    TABLE_METADATA: dict[str, dict] = {
        "issues": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "repositories": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "pull_requests": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "comments": {
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "commits": {
            "primary_keys": ["sha"],
            "ingestion_type": "append",
        },
        "users": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "organizations": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "teams": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "assignees": {
            "primary_keys": ["repository_owner", "repository_name", "id"],
            "ingestion_type": "snapshot",
        },
        "collaborators": {
            "primary_keys": ["repository_owner", "repository_name", "id"],
            "ingestion_type": "snapshot",
        },
        "branches": {
            "primary_keys": ["repository_owner", "repository_name", "name"],
            "ingestion_type": "snapshot",
        },
        "reviews": {
            "primary_keys": ["id"],
            "ingestion_type": "append",
        },
    }
    """Metadata for each table including primary keys, cursor field, and ingestion type."""


    # =============================================================================
    # Supported Tables
    # =============================================================================

    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())
    """List of all table names supported by the GitHub connector."""


    ########################################################
    # src/databricks/labs/community_connector/sources/github/github_utils.py
    ########################################################

    @dataclass
    class PaginationOptions:
        """Configuration options for GitHub API pagination."""

        per_page: int
        lookback_seconds: int
        max_records_per_batch: int | None


    def parse_pagination_options(
        table_options: dict[str, str],
        default_per_page: int = 100,
        default_lookback: int = 300,
    ) -> PaginationOptions:
        """
        Parse common pagination options from table_options.

        Args:
            table_options: Dictionary of table-level configuration options.
            default_per_page: Default page size (max 100 for GitHub API).
            default_lookback: Default lookback window in seconds.

        Returns:
            PaginationOptions with parsed values.
        """
        try:
            per_page = int(table_options.get("per_page", default_per_page))
        except (TypeError, ValueError):
            per_page = default_per_page
        per_page = max(1, min(per_page, 100))

        try:
            lookback_seconds = int(table_options.get("lookback_seconds", default_lookback))
        except (TypeError, ValueError):
            lookback_seconds = default_lookback

        max_records_per_batch: int | None = None
        raw_max_records = table_options.get("max_records_per_batch")
        if raw_max_records is not None:
            try:
                max_records_per_batch = int(raw_max_records)
            except (TypeError, ValueError):
                pass

        return PaginationOptions(
            per_page=per_page,
            lookback_seconds=lookback_seconds,
            max_records_per_batch=max_records_per_batch,
        )


    def extract_next_link(link_header: str | None) -> str | None:
        """
        Parse the GitHub Link header to extract the URL with rel="next".

        The GitHub API uses Link headers for pagination following RFC 5988.
        Format: <url>; rel="next", <url>; rel="last", ...

        Args:
            link_header: The value of the Link header from a GitHub API response.

        Returns:
            The URL for the next page, or None if not found.
        """
        if not link_header:
            return None

        parts = link_header.split(",")
        for part in parts:
            section = part.strip()
            if 'rel="next"' in section:
                # Format: <url>; rel="next"
                start = section.find("<")
                end = section.find(">", start + 1)
                if start != -1 and end != -1:
                    return section[start + 1 : end]
        return None


    def compute_next_cursor(
        max_timestamp: str | None,
        current_cursor: str | None,
    ) -> str | None:
        """
        Return the next cursor value to checkpoint.

        The offset stores the raw max observed timestamp so that progress is never
        lost. Lookback is applied separately at read time via ``apply_lookback``.

        Args:
            max_timestamp: The maximum observed timestamp in ISO 8601 format.
            current_cursor: The current cursor value (fallback when no data found).

        Returns:
            max_timestamp if available, otherwise current_cursor.
        """
        return max_timestamp if max_timestamp else current_cursor


    def apply_lookback(
        cursor: str | None,
        lookback_seconds: int,
        timestamp_format: str = "%Y-%m-%dT%H:%M:%SZ",
    ) -> str | None:
        """
        Subtract a lookback window from a cursor timestamp.

        Used at read time to widen the ``since`` filter so that records updated
        concurrently during the previous batch are not missed.

        Args:
            cursor: ISO 8601 timestamp string to adjust.
            lookback_seconds: Seconds to subtract from cursor.
            timestamp_format: The format of the timestamp string.

        Returns:
            The adjusted timestamp, or the original cursor if parsing fails or
            cursor is None.
        """
        if not cursor or lookback_seconds <= 0:
            return cursor

        try:
            dt = datetime.strptime(cursor, timestamp_format)
            return (dt - timedelta(seconds=lookback_seconds)).strftime(timestamp_format)
        except (ValueError, TypeError):
            return cursor


    def get_cursor_from_offset(
        start_offset: dict | None, table_options: dict[str, str]
    ) -> str | None:
        """
        Extract the cursor value from start_offset or fall back to table_options.

        Args:
            start_offset: The offset dictionary from a previous read.
            table_options: Table-level configuration options.

        Returns:
            The cursor value, or None if not found.
        """
        cursor = None
        if start_offset and isinstance(start_offset, dict):
            cursor = start_offset.get("cursor")
        if not cursor:
            cursor = table_options.get("start_date")
        return cursor


    def require_owner_repo(
        table_options: dict[str, str], table_name: str
    ) -> tuple[str, str]:
        """
        Validate and extract owner and repo from table_options.

        Args:
            table_options: Table-level configuration options.
            table_name: Name of the table (for error message).

        Returns:
            Tuple of (owner, repo).

        Raises:
            ValueError: If owner or repo is missing or empty.
        """
        owner = table_options.get("owner")
        repo = table_options.get("repo")
        if not owner or not repo:
            raise ValueError(
                f"table_configuration for '{table_name}' must include "
                f"non-empty 'owner' and 'repo'"
            )
        return owner, repo


    ########################################################
    # src/databricks/labs/community_connector/sources/github/github.py
    ########################################################

    class GithubLakeflowConnect(LakeflowConnect):
        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the GitHub connector with connection-level options.

            Expected options:
                - token: Personal access token used for GitHub REST API authentication.
                - base_url (optional): Override for GitHub API base URL.
                  Defaults to https://api.github.com.
            """
            token = options.get("token")
            if not token:
                raise ValueError("GitHub connector requires 'token' in options")

            self.base_url = options.get("base_url", "https://api.github.com").rstrip("/")
            self._init_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

            # Configure a session with proper headers for GitHub REST API v3
            self._session = requests.Session()
            self._session.headers.update(
                {
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                }
            )

        def list_tables(self) -> list[str]:
            """
            List names of all tables supported by this connector.

            """
            return SUPPORTED_TABLES.copy()

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """
            Fetch the schema of a table.

            The schema is static and derived from the GitHub REST API documentation
            and connector design for the `issues` object.
            """
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            """
            Fetch metadata for the given table.

            For `issues`:
                - ingestion_type: cdc
                - primary_keys: ["id"]
                - cursor_field: updated_at
            """
            if table_name not in TABLE_METADATA:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_METADATA[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read records from a table and return raw JSON-like dictionaries.

            For the `issues` table this method:
                - Uses `/repos/{owner}/{repo}/issues` endpoint.
                - Supports incremental reads via the `since` query parameter mapped to `updated_at`.
                - Paginates using GitHub's `Link` header until all pages are read or
                  a batch limit (if provided via table_options) is reached.

            Other tables follow similar patterns based on their documented endpoints.

            Required table_options for `issues`:
                - owner: Repository owner (user or organization).
                - repo: Repository name.

            Optional table_options:
                - state: Issue state filter (default: "all").
                - per_page: Page size (max 100, default 100).
                - start_date: Initial ISO 8601 timestamp for first run if no start_offset is provided.
                - lookback_seconds: Lookback window applied to the cursor at read time (default: 300).
                - max_records_per_batch: Optional cap on the number of records returned per
                  read_table call for incremental tables (cdc, append). For CDC tables,
                  records are truncated to this limit. For append-only tables using a
                  sliding window (commits), this is best-effort. Does not apply to
                  snapshot tables.
            """
            reader_map = {
                "issues": self._read_issues,
                "repositories": self._read_repositories,
                "pull_requests": self._read_pull_requests,
                "comments": self._read_comments,
                "commits": self._read_commits,
                "assignees": self._read_assignees,
                "branches": self._read_branches,
                "collaborators": self._read_collaborators,
                "organizations": self._read_organizations,
                "teams": self._read_teams,
                "users": self._read_users,
                "reviews": self._read_reviews,
            }

            if table_name not in reader_map:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return reader_map[table_name](start_offset, table_options)

        def _compute_next_offset(
            self,
            next_cursor: str | None,
            current_cursor: str | None,
            start_offset: dict | None,
            records: list,
        ) -> dict:
            """
            Decide the offset to return from a CDC read.

            The cursor is capped at ``_init_time`` (set once in ``__init__``) so
            that a single trigger run only drains data that existed when the
            connector was instantiated.  Any records arriving after that point
            are still emitted (the API has no upper-bound filter) but the
            checkpoint will not advance past ``_init_time``, guaranteeing
            termination.  The next trigger creates a fresh connector with a
            new ``_init_time``.

            Returns start_offset (signalling "no more data") when either:
            - No records were produced, or
            - The (capped) cursor has not advanced beyond current_cursor.
            """
            if not records and start_offset:
                return start_offset

            if not next_cursor:
                return start_offset if start_offset else {}

            next_cursor = min(next_cursor, self._init_time)

            if next_cursor == current_cursor:
                return start_offset if start_offset else {"cursor": next_cursor}

            return {"cursor": next_cursor}

        def _paginated_fetch(
            self,
            url: str,
            params: dict,
            pagination: PaginationOptions,
            entity_name: str,
        ) -> list[dict]:
            """
            Generic paginated fetch from GitHub API.

            Follows ``rel="next"`` Link headers until all pages are consumed.

            Args:
                url: The API endpoint URL.
                params: Query parameters for the request.
                pagination: Pagination configuration (used for per_page).
                entity_name: Name of the entity being fetched (for error messages).

            Returns:
                List of raw JSON objects from all fetched pages.
            """
            results: list[dict] = []
            next_url: str | None = url
            next_params: dict | None = params

            while next_url:
                response = self._session.get(next_url, params=next_params, timeout=30)
                if response.status_code != 200:
                    raise RuntimeError(
                        f"GitHub API error for {entity_name}: {response.status_code} {response.text}"
                    )

                data = response.json() or []
                if not isinstance(data, list):
                    raise ValueError(
                        f"Unexpected response format for {entity_name}: {type(data).__name__}"
                    )

                results.extend(data)

                link_header = response.headers.get("Link", "")
                next_url = extract_next_link(link_header)
                next_params = None

            return results

        def _read_issues(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """Internal implementation for reading the `issues` table."""
            owner, repo = require_owner_repo(table_options, "issues")
            pagination = parse_pagination_options(table_options)
            state = table_options.get("state", "all")
            cursor = get_cursor_from_offset(start_offset, table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/issues"
            params = {
                "state": state,
                "per_page": pagination.per_page,
                "sort": "updated",
                "direction": "asc",
            }
            since = apply_lookback(cursor, pagination.lookback_seconds)
            if since:
                params["since"] = since

            raw_issues = self._paginated_fetch(url, params, pagination, "issues")

            max_records = pagination.max_records_per_batch
            records: list[dict[str, Any]] = []
            max_updated_at: str | None = None

            for issue in raw_issues:
                record: dict[str, Any] = dict(issue)
                record["repository_owner"] = owner
                record["repository_name"] = repo
                records.append(record)

                updated_at = record.get("updated_at")
                if isinstance(updated_at, str):
                    if max_updated_at is None or updated_at > max_updated_at:
                        max_updated_at = updated_at

                if max_records is not None and len(records) >= max_records:
                    break

            next_cursor = compute_next_cursor(max_updated_at, cursor)
            next_offset = self._compute_next_offset(
                next_cursor, cursor, start_offset, records
            )

            return iter(records), next_offset

        def _read_repositories(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `repositories` snapshot table.

            This implementation lists repositories for a given user or organization
            using the GitHub REST API:

                - GET /users/{username}/repos
                - GET /orgs/{org}/repos

            The returned JSON objects already have the full repository shape described
            in the connector schema. We add connector-derived fields:
                - repository_owner: owner.login
                - repository_name: name

            Required table_options:
                - Either:
                  - owner: GitHub username (for /users/{username}/repos)
                  - or org: GitHub organization login (for /orgs/{org}/repos)

            Optional table_options:
                - per_page: Page size (max 100, default 100).
            """
            owner = table_options.get("owner")
            org = table_options.get("org")

            if owner and org:
                raise ValueError(
                    "table_configuration for 'repositories' must not include both "
                    "'owner' and 'org'; specify only one."
                )
            if not owner and not org:
                raise ValueError(
                    "table_configuration for 'repositories' must include either "
                    "'owner' (username) or 'org' (organization login)"
                )

            pagination = parse_pagination_options(table_options)

            if org:
                url = f"{self.base_url}/orgs/{org}/repos"
            else:
                url = f"{self.base_url}/users/{owner}/repos"

            params = {"per_page": pagination.per_page}

            raw_repos = self._paginated_fetch(url, params, pagination, "repositories")

            records: list[dict[str, Any]] = []
            for repo_obj in raw_repos:
                record: dict[str, Any] = dict(repo_obj)
                owner_obj = repo_obj.get("owner") or {}
                record["repository_owner"] = owner_obj.get("login")
                record["repository_name"] = repo_obj.get("name")
                records.append(record)

            return iter(records), {}

        def _read_pull_requests(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `pull_requests` cdc table using:
                GET /repos/{owner}/{repo}/pulls

            Incremental behaviour mirrors issues using updated_at as a cursor,
            but for now this implementation always performs a forward read
            from the provided (optional) cursor.
            """
            owner, repo = require_owner_repo(table_options, "pull_requests")
            pagination = parse_pagination_options(table_options)
            state = table_options.get("state", "all")
            cursor = get_cursor_from_offset(start_offset, table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/pulls"
            params = {
                "state": state,
                "per_page": pagination.per_page,
                "sort": "updated",
                "direction": "asc",
            }
            since = apply_lookback(cursor, pagination.lookback_seconds)
            if since:
                params["since"] = since

            raw_prs = self._paginated_fetch(url, params, pagination, "pull_requests")

            max_records = pagination.max_records_per_batch
            records: list[dict[str, Any]] = []
            max_updated_at: str | None = None

            for pr in raw_prs:
                record: dict[str, Any] = dict(pr)
                record["repository_owner"] = owner
                record["repository_name"] = repo
                records.append(record)

                updated_at = record.get("updated_at")
                if isinstance(updated_at, str):
                    if max_updated_at is None or updated_at > max_updated_at:
                        max_updated_at = updated_at

                if max_records is not None and len(records) >= max_records:
                    break

            next_cursor = compute_next_cursor(max_updated_at, cursor)
            next_offset = self._compute_next_offset(
                next_cursor, cursor, start_offset, records
            )

            return iter(records), next_offset

        def _read_comments(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `comments` cdc table using:
                GET /repos/{owner}/{repo}/issues/comments
            """
            owner, repo = require_owner_repo(table_options, "comments")
            pagination = parse_pagination_options(table_options)
            cursor = get_cursor_from_offset(start_offset, table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/issues/comments"
            params = {
                "per_page": pagination.per_page,
                "sort": "updated",
                "direction": "asc",
            }
            since = apply_lookback(cursor, pagination.lookback_seconds)
            if since:
                params["since"] = since

            raw_comments = self._paginated_fetch(url, params, pagination, "comments")

            max_records = pagination.max_records_per_batch
            records: list[dict[str, Any]] = []
            max_updated_at: str | None = None

            for comment in raw_comments:
                record: dict[str, Any] = dict(comment)
                record["repository_owner"] = owner
                record["repository_name"] = repo
                records.append(record)

                updated_at = record.get("updated_at")
                if isinstance(updated_at, str):
                    if max_updated_at is None or updated_at > max_updated_at:
                        max_updated_at = updated_at

                if max_records is not None and len(records) >= max_records:
                    break

            next_cursor = compute_next_cursor(max_updated_at, cursor)
            next_offset = self._compute_next_offset(
                next_cursor, cursor, start_offset, records
            )

            return iter(records), next_offset

        def _find_oldest_commit_date(self, owner: str, repo: str) -> str | None:
            """Discover the committer date of the oldest commit in the repo.

            Uses two lightweight API calls: one ``per_page=1`` request to read the
            ``rel="last"`` Link header, then one request to fetch that last page.
            """
            url = f"{self.base_url}/repos/{owner}/{repo}/commits"
            resp = self._session.get(url, params={"per_page": 1}, timeout=30)
            if resp.status_code != 200:
                return None

            link_header = resp.headers.get("Link", "")
            last_url = None
            for part in link_header.split(","):
                section = part.strip()
                if 'rel="last"' in section:
                    start = section.find("<")
                    end = section.find(">", start + 1)
                    if start != -1 and end != -1:
                        last_url = section[start + 1 : end]

            if not last_url:
                # Only one page — the single commit in the initial response is the oldest.
                data = resp.json()
                if data:
                    committer = (data[-1].get("commit") or {}).get("committer") or {}
                    return committer.get("date")
                return None

            last_resp = self._session.get(last_url, timeout=30)
            if last_resp.status_code != 200:
                return None
            data = last_resp.json()
            if data:
                committer = (data[-1].get("commit") or {}).get("committer") or {}
                return committer.get("date")
            return None

        def _read_commits(  # pylint: disable=too-many-locals
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the ``commits`` append-only table using:
                GET /repos/{owner}/{repo}/commits

            The commits API returns results newest-first with no sort parameter.
            ``since``/``until`` filter on **committer date**.  This method uses a
            sliding time-window to scope each API query, but compacts multiple
            consecutive windows into a single batch until ``max_records_per_batch``
            is reached, the cursor hits ``_init_time``, or a window returns empty.

            When no ``start_date`` or prior offset is available the connector
            auto-discovers the oldest commit date via two lightweight API calls.
            """
            owner, repo = require_owner_repo(table_options, "commits")
            pagination = parse_pagination_options(table_options)
            cursor = get_cursor_from_offset(start_offset, table_options)

            if not cursor:
                cursor = self._find_oldest_commit_date(owner, repo)
            if not cursor:
                return iter([]), start_offset if start_offset else {}

            if cursor >= self._init_time:
                return iter([]), start_offset if start_offset else {}

            seven_days = 7 * 24 * 60 * 60
            try:
                window_seconds = int(table_options.get("window_seconds", str(seven_days)))
            except (TypeError, ValueError):
                window_seconds = seven_days

            max_records = pagination.max_records_per_batch
            ts_fmt = "%Y-%m-%dT%H:%M:%SZ"
            url = f"{self.base_url}/repos/{owner}/{repo}/commits"

            records: list[dict[str, Any]] = []
            window_cursor = cursor

            while window_cursor < self._init_time:
                window_end_dt = datetime.strptime(window_cursor, ts_fmt) + timedelta(
                    seconds=window_seconds
                )
                window_end = min(window_end_dt.strftime(ts_fmt), self._init_time)

                params: dict[str, Any] = {
                    "per_page": pagination.per_page,
                    "since": window_cursor,
                    "until": window_end,
                }

                raw_commits = self._paginated_fetch(url, params, pagination, "commits")

                if not raw_commits:
                    window_cursor = window_end
                    continue

                for commit_obj in raw_commits:
                    commit_info = commit_obj.get("commit", {}) or {}
                    commit_author = commit_info.get("author", {}) or {}
                    commit_committer = commit_info.get("committer", {}) or {}

                    record: dict[str, Any] = {
                        "sha": commit_obj.get("sha"),
                        "node_id": commit_obj.get("node_id"),
                        "repository_owner": owner,
                        "repository_name": repo,
                        "commit_message": commit_info.get("message"),
                        "commit_author_name": commit_author.get("name"),
                        "commit_author_email": commit_author.get("email"),
                        "commit_author_date": commit_author.get("date"),
                        "commit_committer_name": commit_committer.get("name"),
                        "commit_committer_email": commit_committer.get("email"),
                        "commit_committer_date": commit_committer.get("date"),
                        "html_url": commit_obj.get("html_url"),
                        "url": commit_obj.get("url"),
                        "author": commit_obj.get("author"),
                        "committer": commit_obj.get("committer"),
                    }
                    records.append(record)

                window_cursor = window_end

                if max_records is not None and len(records) >= max_records:
                    break

            if not records:
                return iter([]), start_offset if start_offset else {"cursor": cursor}

            end_offset: dict[str, Any] = {"cursor": window_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        def _read_assignees(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `assignees` snapshot table using:
                GET /repos/{owner}/{repo}/assignees
            """
            owner, repo = require_owner_repo(table_options, "assignees")
            pagination = parse_pagination_options(table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/assignees"
            params = {"per_page": pagination.per_page}

            raw_assignees = self._paginated_fetch(url, params, pagination, "assignees")

            records: list[dict[str, Any]] = []
            for assignee in raw_assignees:
                record: dict[str, Any] = {
                    "repository_owner": owner,
                    "repository_name": repo,
                    "login": assignee.get("login"),
                    "id": assignee.get("id"),
                    "node_id": assignee.get("node_id"),
                    "type": assignee.get("type"),
                    "site_admin": assignee.get("site_admin"),
                }
                records.append(record)

            return iter(records), {}

        def _read_branches(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `branches` snapshot table using:
                GET /repos/{owner}/{repo}/branches
            """
            owner, repo = require_owner_repo(table_options, "branches")
            pagination = parse_pagination_options(table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/branches"
            params = {"per_page": pagination.per_page}

            raw_branches = self._paginated_fetch(url, params, pagination, "branches")

            records: list[dict[str, Any]] = []
            for branch in raw_branches:
                record: dict[str, Any] = {
                    "repository_owner": owner,
                    "repository_name": repo,
                    "name": branch.get("name"),
                    "commit": branch.get("commit"),
                    "protected": branch.get("protected"),
                    "protection_url": branch.get("protection_url"),
                }
                records.append(record)

            return iter(records), {}

        def _read_collaborators(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `collaborators` snapshot table using:
                GET /repos/{owner}/{repo}/collaborators
            """
            owner, repo = require_owner_repo(table_options, "collaborators")
            pagination = parse_pagination_options(table_options)

            url = f"{self.base_url}/repos/{owner}/{repo}/collaborators"
            params = {"per_page": pagination.per_page}

            raw_collaborators = self._paginated_fetch(url, params, pagination, "collaborators")

            records: list[dict[str, Any]] = []
            for collaborator in raw_collaborators:
                record: dict[str, Any] = {
                    "repository_owner": owner,
                    "repository_name": repo,
                    "login": collaborator.get("login"),
                    "id": collaborator.get("id"),
                    "node_id": collaborator.get("node_id"),
                    "type": collaborator.get("type"),
                    "site_admin": collaborator.get("site_admin"),
                    "permissions": collaborator.get("permissions"),
                }
                records.append(record)

            return iter(records), {}

        def _read_organizations(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `organizations` snapshot table.

            Instead of requiring an explicit `org` option, this method discovers
            organizations for the authenticated user using:

                - GET /user/orgs                  (list orgs the token can see)

            It intentionally does **not** expand each organization via
            `GET /orgs/{org}` to avoid additional permission requirements on
            the detail endpoint. The table therefore exposes the summary
            metadata returned directly by `GET /user/orgs`.
            """
            pagination = parse_pagination_options(table_options)

            url = f"{self.base_url}/user/orgs"
            params = {"per_page": pagination.per_page}

            raw_orgs = self._paginated_fetch(url, params, pagination, "organizations")

            records: list[dict[str, Any]] = []
            for org_summary in raw_orgs:
                if not isinstance(org_summary, dict):
                    continue

                record: dict[str, Any] = {
                    "id": org_summary.get("id"),
                    "login": org_summary.get("login"),
                    "node_id": org_summary.get("node_id"),
                    "url": org_summary.get("url"),
                    "repos_url": org_summary.get("repos_url"),
                    "events_url": org_summary.get("events_url"),
                    "hooks_url": org_summary.get("hooks_url"),
                    "issues_url": org_summary.get("issues_url"),
                    "members_url": org_summary.get("members_url"),
                    "public_members_url": org_summary.get("public_members_url"),
                    "avatar_url": org_summary.get("avatar_url"),
                    "description": org_summary.get("description"),
                }
                records.append(record)

            return iter(records), {}

        def _read_teams(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `teams` snapshot table.

            Instead of requiring an explicit `org` option, this method discovers
            teams for the authenticated user using:

                - GET /user/teams                          (list teams user can see)
                - GET /orgs/{org}/teams/{team_slug}        (expand each team)

            The connector also adds `organization_login` to each record to match
            the declared schema.
            """
            pagination = parse_pagination_options(table_options)

            url = f"{self.base_url}/user/teams"
            params = {"per_page": pagination.per_page}

            raw_teams = self._paginated_fetch(url, params, pagination, "teams")

            records: list[dict[str, Any]] = []
            for team_summary in raw_teams:
                org_obj = team_summary.get("organization") or {}
                org_login = org_obj.get("login")
                team_slug = team_summary.get("slug")
                if not org_login or not team_slug:
                    continue

                detail_url = f"{self.base_url}/orgs/{org_login}/teams/{team_slug}"
                detail_resp = self._session.get(detail_url, timeout=30)
                if detail_resp.status_code != 200:
                    raise RuntimeError(
                        f"GitHub API error for team {org_login!r}/{team_slug!r}: "
                        f"{detail_resp.status_code} {detail_resp.text}"
                    )

                team_obj = detail_resp.json() or {}
                if not isinstance(team_obj, dict):
                    raise ValueError(
                        f"Unexpected response format for team detail: {type(team_obj).__name__}"
                    )

                record: dict[str, Any] = dict(team_obj)
                record["organization_login"] = org_login
                records.append(record)

            return iter(records), {}

        def _read_users(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `users` snapshot table using:
                GET /user

            The connector now resolves the user from the authenticated context and
            no longer requires a `username` option. This returns metadata for the
            current authenticated user.
            """
            url = f"{self.base_url}/user"
            response = self._session.get(url, timeout=30)
            if response.status_code != 200:
                raise RuntimeError(
                    f"GitHub API error for users: {response.status_code} {response.text}"
                )

            user_obj = response.json() or {}
            if not isinstance(user_obj, dict):
                raise ValueError(
                    f"Unexpected response format for user: {type(user_obj).__name__}"
                )

            record: dict[str, Any] = dict(user_obj)
            return iter([record]), {}

        def _read_reviews(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> (Iterator[dict], dict):
            """
            Read the `reviews` append-only table.

            Primary child API:
                - GET /repos/{owner}/{repo}/pulls/{pull_number}/reviews

            Parent listing when pull_number is not provided (see Step 3 guidance in
            the connector coding instructions about parent/child relationships):
                - GET /repos/{owner}/{repo}/pulls
                  Then for each pull request, call the reviews API above and
                  combine all reviews into a single logical table.
            """
            owner, repo = require_owner_repo(table_options, "reviews")
            pagination = parse_pagination_options(table_options)
            pull_number_opt = table_options.get("pull_number")

            max_records = pagination.max_records_per_batch
            records: list[dict[str, Any]] = []

            def _fetch_reviews_for_pull(pull_number: int) -> None:
                """Fetch reviews for a single pull request and append to records."""
                url = f"{self.base_url}/repos/{owner}/{repo}/pulls/{pull_number}/reviews"
                params = {"per_page": pagination.per_page}

                raw_reviews = self._paginated_fetch(
                    url, params, pagination, f"reviews for PR #{pull_number}"
                )

                for review in raw_reviews:
                    record: dict[str, Any] = dict(review)
                    record["repository_owner"] = owner
                    record["repository_name"] = repo
                    record["pull_number"] = int(pull_number)
                    records.append(record)

            if pull_number_opt is not None:
                try:
                    pull_number_int = int(pull_number_opt)
                except (TypeError, ValueError) as exc:
                    raise ValueError(
                        f"table_options['pull_number'] must be an int-compatible value, "
                        f"got {pull_number_opt!r}"
                    ) from exc

                _fetch_reviews_for_pull(pull_number_int)
                return iter(records), {}

            pr_state = table_options.get("state", "all")
            url = f"{self.base_url}/repos/{owner}/{repo}/pulls"
            params = {"state": pr_state, "per_page": pagination.per_page}

            raw_prs = self._paginated_fetch(url, params, pagination, "pull_requests")

            for pr in raw_prs:
                if max_records is not None and len(records) >= max_records:
                    break
                number = pr.get("number")
                if isinstance(number, int):
                    _fetch_reviews_for_pull(number)

            return iter(records), {}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = GithubLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
