# ==============================================================================
# Merged Lakeflow Source: example
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from databricks.labs.community_connector.libs.simulated_source.api import get_api
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/example/example_schemas.py
    ########################################################

    SPARK_TYPE_MAP = {
        "string": StringType(),
        "integer": LongType(),
        "double": DoubleType(),
        "timestamp": TimestampType(),
        "date": DateType(),
    }

    # Tables whose ingestion type cannot be inferred from metadata alone.
    # The API does not expose ingestion type directly; these overrides are
    # applied before the fallback logic (cursor_field present → cdc, absent → snapshot).
    INGESTION_TYPE_OVERRIDES = {
        "metrics": "cdc",
        "events": "append",
        "orders": "cdc_with_deletes",
    }

    # Hard-coded schema for the hidden ``metrics`` table whose /schema
    # endpoint returns 404.  The ``value`` column is a nested struct.
    METRICS_SCHEMA = StructType(
        [
            StructField("metric_id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField(
                "value",
                StructType(
                    [
                        StructField("count", LongType(), nullable=True),
                        StructField("label", StringType(), nullable=True),
                        StructField("measure", DoubleType(), nullable=True),
                    ]
                ),
                nullable=True,
            ),
            StructField("host", StringType(), nullable=True),
            StructField("updated_at", TimestampType(), nullable=False),
        ]
    )

    METRICS_METADATA = {
        "primary_keys": ["metric_id"],
        "cursor_field": "updated_at",
    }

    RETRIABLE_STATUS_CODES = {429, 500, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry


    def build_spark_type(field_descriptor: dict) -> StructField:
        """Convert an API field descriptor to a Spark ``StructField``.

        Recurses into nested ``fields`` for ``struct`` types so the full
        hierarchy is preserved without flattening.
        """
        field_type = field_descriptor["type"]
        if field_type == "struct":
            children = [build_spark_type(f) for f in field_descriptor.get("fields", [])]
            spark_type = StructType(children)
        else:
            spark_type = SPARK_TYPE_MAP[field_type]
        return StructField(
            field_descriptor["name"],
            spark_type,
            nullable=field_descriptor.get("nullable", True),
        )


    ########################################################
    # src/databricks/labs/community_connector/sources/example/example.py
    ########################################################

    class ExampleLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the simulated Example source."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            username = options.get("username", "default_user")
            password = options.get("password", "default_pass")
            self._api = get_api(username, password)

            # Cap cursors at init time so a trigger never chases new data.
            # The next trigger creates a fresh instance and picks up from here.
            self._init_ts = datetime.now(timezone.utc).isoformat()

        def _request_with_retry(self, method: str, path: str, **kwargs):
            """Issue an API request, retrying on 429/500/503 with exponential backoff."""
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                if method == "GET":
                    resp = self._api.get(path, **kwargs)
                else:
                    raise ValueError(f"Unsupported HTTP method: {method}")

                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                if attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2

            return resp

        def list_tables(self) -> list[str]:
            """Discoverable tables from the API plus the hidden ``metrics`` table."""
            resp = self._request_with_retry("GET", "/tables")
            tables = resp.json()["tables"]
            tables.append("metrics")  # static table that cannot be discovered via the API
            return tables

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """Return the Spark schema.  Hard-coded for ``metrics``; fetched from the API otherwise."""
            self._validate_table(table_name)
            if table_name == "metrics":
                return METRICS_SCHEMA

            resp = self._request_with_retry("GET", f"/tables/{table_name}/schema")
            if resp.status_code != 200:
                raise RuntimeError(f"Failed to get schema for '{table_name}': {resp.json()}")
            fields = resp.json()["schema"]
            return StructType([build_spark_type(f) for f in fields])

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            """Return metadata with ingestion type resolved via hard-coded overrides
            then the cursor_field presence fallback."""
            self._validate_table(table_name)
            if table_name == "metrics":
                metadata = dict(METRICS_METADATA)
            else:
                resp = self._request_with_retry("GET", f"/tables/{table_name}/metadata")
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to get metadata for '{table_name}': {resp.json()}")
                metadata = dict(resp.json()["metadata"])

            if table_name in INGESTION_TYPE_OVERRIDES:
                metadata["ingestion_type"] = INGESTION_TYPE_OVERRIDES[table_name]
            elif metadata.get("cursor_field"):
                metadata["ingestion_type"] = "cdc"
            else:
                metadata["ingestion_type"] = "snapshot"

            return metadata

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Route to snapshot or incremental read based on ingestion type."""
            self._validate_table(table_name)
            metadata = self.read_table_metadata(table_name, table_options)
            ingestion_type = metadata["ingestion_type"]

            if ingestion_type == "snapshot":
                return self._read_snapshot(table_name, table_options)

            cursor_field = metadata.get("cursor_field")
            if table_name == "events":
                return self._read_incremental_by_limit(
                    table_name, start_offset, table_options, cursor_field
                )
            if table_name == "metrics":
                return self._read_incremental_by_window(
                    table_name, start_offset, table_options, cursor_field
                )
            return self._read_incremental(table_name, start_offset, table_options, cursor_field)

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Fetch deleted-record tombstones.  Only ``orders`` supports this endpoint."""
            self._validate_table(table_name)
            if table_name != "orders":
                raise ValueError(f"Table '{table_name}' does not support deleted records")

            since = start_offset.get("cursor") if start_offset else None
            # Already caught up to init time — skip the API call entirely.
            if since and since >= self._init_ts:
                return iter([]), start_offset

            max_records = int(table_options.get("max_records_per_batch", "200"))

            records = []
            page = 1
            while len(records) < max_records:
                params = {"page": str(page)}
                if since:
                    params["since"] = since

                resp = self._request_with_retry("GET", "/tables/orders/deleted_records", params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read deleted records for 'orders': {resp.json()}")

                body = resp.json()
                batch = body["records"]
                if not batch:
                    break

                records.extend(batch)

                if body["next_page"] is None:
                    break
                page = body["next_page"]

            if not records:
                return iter([]), start_offset or {}

            # Records are sorted by cursor — last record has the max.
            last_cursor = records[-1]["updated_at"]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def _validate_table(self, table_name: str) -> None:
            supported = self.list_tables()
            if table_name not in supported:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {supported}"
                )

        def _read_snapshot(
            self, table_name: str, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Full-refresh read.  Paginates through all pages and returns offset=None."""
            records = []
            page = 1
            params = {}

            if table_name == "products" and "category" in table_options:
                params["category"] = table_options["category"]

            while True:
                params["page"] = str(page)
                resp = self._request_with_retry("GET", f"/tables/{table_name}/records", params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read records from '{table_name}': {resp.json()}")

                body = resp.json()
                records.extend(body["records"])

                if body["next_page"] is None:
                    break
                page = body["next_page"]

            return iter(records), {}  # no offset for snapshot reads

        def _read_incremental(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """Record-count–based incremental read for cdc and cdc_with_deletes tables.

            Respects ``max_records_per_batch`` from *table_options* to limit the
            microbatch size.  Safe for CDC tables where primary-key–based upsert
            semantics tolerate duplicate deliveries.
            """
            since = start_offset.get("cursor") if start_offset else None
            # Already caught up to init time — skip the API call entirely.
            if since and since >= self._init_ts:
                return iter([]), start_offset

            max_records = int(table_options.get("max_records_per_batch", "200"))

            params = {}
            if since:
                params["since"] = since

            if table_name == "orders":
                for opt_key in ("user_id", "status"):
                    if opt_key in table_options:
                        params[opt_key] = table_options[opt_key]

            records = []
            page = 1
            while len(records) < max_records:
                params["page"] = str(page)
                resp = self._request_with_retry("GET", f"/tables/{table_name}/records", params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read records from '{table_name}': {resp.json()}")

                body = resp.json()
                batch = body["records"]
                if not batch:
                    break

                records.extend(batch)

                if body["next_page"] is None:
                    break
                page = body["next_page"]

            if not records:
                return iter([]), start_offset or {}

            # Records are sorted by cursor — last record has the max.
            last_cursor = records[-1][cursor_field]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def _read_incremental_by_limit(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """Limit-before-fetch incremental read for append_only tables.

            Each API call receives a small ``limit`` so the server controls
            the batch boundary — no client-side truncation.  Calls repeat
            until ``max_records_per_batch`` is reached or the last record
            reaches ``_init_ts``.  The actual total may be approximate since
            we never cut within a server response.
            """
            since = start_offset.get("cursor") if start_offset else None
            # Already caught up to init time — skip the API call entirely.
            if since and since >= self._init_ts:
                return iter([]), start_offset

            limit = int(table_options.get("limit", "50"))
            max_records = int(table_options.get("max_records_per_batch", "200"))

            params = {"limit": str(limit)}
            if since:
                params["since"] = since

            records = []
            page = 1
            while len(records) < max_records:
                params["page"] = str(page)
                resp = self._request_with_retry("GET", f"/tables/{table_name}/records", params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read records from '{table_name}': {resp.json()}")

                body = resp.json()
                batch = body["records"]
                if not batch:
                    break

                records.extend(batch)

                # Stop when the last record reached init time — stream caught up.
                if batch[-1].get(cursor_field, "") >= self._init_ts:
                    break

                if body["next_page"] is None:
                    break
                page = body["next_page"]

            if not records:
                return iter([]), start_offset or {}

            # Records are sorted by cursor — last record has the max.
            last_cursor = records[-1][cursor_field]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def _peek_oldest_cursor(
            self, table_name: str, cursor_field: str
        ) -> str | None:
            """Discover the oldest cursor value by fetching page 1 with no filters.

            The API returns records sorted ascending by cursor field, so the
            first record on the first page is the oldest.
            """
            resp = self._request_with_retry(
                "GET", f"/tables/{table_name}/records", params={"page": "1"}
            )
            if resp.status_code != 200:
                return None
            batch = resp.json().get("records", [])
            if batch:
                return batch[0].get(cursor_field)
            return None

        def _read_incremental_by_window(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
            cursor_field: str,
        ) -> tuple[Iterator[dict], dict]:
            """Sliding time-window incremental read for large-volume tables.

            Queries data in fixed-size windows using ``since``/``until``
            parameters, paginates within each window, then advances the
            cursor to the window end.  The window size is controlled by
            ``window_seconds`` in *table_options* (default 3600).
            ``max_records_per_batch`` caps the records per call as a safety
            bound in case the window contains more data than expected.

            When no cursor is available, the method first checks
            ``start_timestamp`` in *table_options* (user-supplied lower
            bound).  If that is also absent, it peeks at page 1 of the
            API to discover the oldest record's cursor value.  This
            ensures the first call always has a bounded ``since``.
            """
            since = start_offset.get("cursor") if start_offset else None
            if not since:
                since = table_options.get("start_timestamp")
            if not since:
                since = self._peek_oldest_cursor(table_name, cursor_field)
            if not since:
                raise ValueError(
                    f"Cannot determine starting cursor for '{table_name}'. "
                    f"Provide 'start_timestamp' in table_options."
                )

            if since >= self._init_ts:
                return iter([]), start_offset if start_offset else {}

            window_seconds = int(table_options.get("window_seconds", "3600"))
            max_records = int(table_options.get("max_records_per_batch", "200"))

            window_end_dt = datetime.fromisoformat(since) + timedelta(seconds=window_seconds)
            window_end = min(window_end_dt.isoformat(), self._init_ts)

            params = {"since": since, "until": window_end}

            records = []
            page = 1
            while len(records) < max_records:
                params["page"] = str(page)
                resp = self._request_with_retry("GET", f"/tables/{table_name}/records", params=params)
                if resp.status_code != 200:
                    raise RuntimeError(f"Failed to read records from '{table_name}': {resp.json()}")

                body = resp.json()
                batch = body["records"]
                if not batch:
                    break

                records.extend(batch)

                if body["next_page"] is None:
                    break
                page = body["next_page"]

            if not records:
                end_offset = {"cursor": window_end}
                if start_offset and start_offset == end_offset:
                    return iter([]), start_offset
                return iter([]), end_offset

            # Records are sorted ascending by cursor — last record has the max.
            last_cursor = records[-1][cursor_field]
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset

            return iter(records), end_offset


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = ExampleLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
